version: '2'
services:
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --sql_mode="" --secure-file-priv=""
    environment:
      - MYSQL_ROOT_PASSWORD=app
      - MYSQL_DATABASE=app
    ports:
      - "3306:3306"
  nginx:
    image: nginx:1.12-alpine
    volumes:
      - ./src/:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/upstream.conf:/etc/nginx/conf.d/upstream.conf
    ports:
      - "8000:80"
    links:
      - php-fpm
  php-fpm:
    build:
      context: ./docker/php-fpm/
    volumes:
      - ./src/:/var/www/html
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/conf.d/zzmyphp.ini
    links:
      - db
